name: Aqua PPL
on:
  workflow_dispatch:
jobs:
  ImgScan:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v4 
      - name: Build local images
        run: docker build -t rurouniken89/nodejsappgod .
      - name: check images
        run: docker images
      - name: docker login
        env:
          AQUAREGISTRY_USER: sarunyu.r@netpoleons.com
          AQUAREGISTRY_PASS: WWUdyu58$e
          AQUASCANNER_USER: ken-scanner
          AQUASCANNER_PASS: P@ssw0rd
        run: 'script: echo ${AQUAREGISTRY_PASS} | docker login -u ${AQUAREGISTRY_USER} --password-stdin registry.aquasec.com'
