name: dep
on:
  #push:
    #branches: [ "main" ]
  workflow_dispatch:
jobs:
  Deploy_Images:
    runs-on: kencentrun
    container: node:14
    steps:
      - name : To_DockerfileDir
        run : cd /home/admin/testpplgod/pipelinegod/
      - name : Deploy_images
        run : docker compose up -d --build --force-recreate
      - name : stall for MySQL up
        uses: juliangruber/sleep-action@v2.0.0
        with:
          time: 20s
      - name: Full deploy
        run : docker compose up -d --build --force-recreate app
