name: KenPPLgod
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  SAST:
    runs-on: kencentrun
    container: node:14
    steps:    
      - name: Check out source code
        uses: actions/checkout@v3
      - name: debug
        uses: github/command@v1.1.0
        with:
          command: "pwd; ls -l"
      - name: Run ScanCentral SAST Scan
        uses: fortify/github-action/sc-sast-scan@v1
      - name: scanstarted  
        run:  scancentral -url $SC_CONTROLLER_URL start $BUILD_OPTS $SCAN_OPTS -upload -application pplgod -version 1 -uptoken $SSC_UPLOAD_TOKEN -fprssc $SSC_APPVERSION-$BUILD_NO.fpr
        env:
          SC_CONTROLLER_URL: ${{ vars.SC_CONTROLLER_URL }} 
          SSC_URL: ${{secrets.SSC_URL}}
          SSC_UPLOAD_TOKEN: ${{secrets.SSC_UPLOAD_TOKEN}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SC_SAST_TOKEN: ${{secrets.CLIENT_AUTH_TOKEN}}
          EXTRA_SC_SAST_LOGIN_OPTS: --socket-timeout=60s
          SSC_APPVERSION: pplgod:1
          # EXTRA_PACKAGE_OPTS: -bf custom-pom.xml
          SC_SAST_SENSOR_VERSION: 23.1
          BUILD_OPTS: "-bt none"
          # DO_WAIT: true
          # DO_EXPORT: true
          # TOOL_DEFINITIONS: https://ftfy.mycompany.com/tool-definitions/v1/tool-definitions.yaml.zip
